version: '3'

services:
  queueio:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - '8000:80'
    networks:
      - mynetwork
    restart: always
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - mynetwork

networks:
  mynetwork:
